namespace = ZZZStateAndOutfitDetection

;==================================================
; ZZZ State and Outfit Detection
; Version: 0.081
;
; Made by: MirariLP
; Inspired by: https://gamebanana.com/tools/15459
;
; Namespace:
;   All persist variables are accessible under \ZZZStateAndOutfitDetection
;
; Usage Example:
;   if $\ZZZStateAndOutfitDetection\districtAndCombatCheck == 1
;       * something *
;   endif
;==================================================

; Values for $districtAndCombatCheck:
; 0: nothing identified
; 1: combat
; 2: freeroam

; Values for $belleOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: yunkui summit outfit
; 3: swimsuit outfit

; Values for $wiseOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: yunkui summit outfit
; 3: swimsuit outfit

; Values for $nicoleOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: cutie outfit

; Values for $vivianOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: swimsuit outfit

; Values for $yuzuhaOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: swimsuit outfit

; Values for $aliceOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: swimsuit outfit

; Values for $sunnaOutfitCheck:
; 0: nothing identified
; 1: default outfit
; 2: maid outfit

;------------------------
; Update Log:
; v0.01 	- Added combat and freeroam check
; v0.02 	- Added Belle and Wise outfit check (default + yunkui summit)
; v0.03 	- Added compatibility with Aerospace City
; v0.04 	- Added Yuzuha and Alice outfit check (default + swimsuit)
; v0.05		- Added Belle and Wise swimsuit outfit check
; v0.06		- Added Nicole outfit check (default + cutie)
; v0.061	- Updated combat detection for version 2.2
; v0.062	- Updated combat detection for version 2.3
; v0.07		- Added Vivian outfit check (default + swimsuit)
; v0.071	- Updated combat detection for version 2.5
; v0.08		- Added Sunna outfit check (default + maid)
; v0.081	- Updated Belle's yunkui summit hash
;------------------------

[Constants]
; District and Combat variables
global $combat = 0
global $combatAerospaceCity = 0
global $freeroam = 0
global persist $districtAndCombatCheck = 0
;--------------------------------

; Belle Outfit variables
global $belleDefaultOutfit = 0
global $belleYunkuiOutfit = 0
global $belleSwimsuitOutfit = 0
global persist $belleOutfitCheck = 0
;--------------------------------

; Wise Outfit variables
global $wiseDefaultOutfit = 0
global $wiseYunkuiOutfit = 0
global $wiseSwimsuitOutfit = 0
global persist $wiseOutfitCheck = 0
;--------------------------------

; Nicole Outfit variables
global $nicoleDefaultOutfit = 0
global $nicoleCutieOutfit = 0
global persist $nicoleOutfitCheck = 0
;--------------------------------

; Vivian Outfit variables
global $vivianDefaultOutfit = 0
global $vivianSwimsuitOutfit = 0
global persist $vivianOutfitCheck = 0
;--------------------------------

; Yuzuha Outfit variables
global $yuzuhaDefaultOutfit = 0
global $yuzuhaSwimsuitOutfit = 0
global persist $yuzuhaOutfitCheck = 0
;--------------------------------

; Alice Outfit variables
global $aliceDefaultOutfit = 0
global $aliceSwimsuitOutfit = 0
global persist $aliceOutfitCheck = 0
;--------------------------------

; Sunna Outfit variables
global $sunnaDefaultOutfit = 0
global $sunnaMaidOutfit = 0
global persist $sunnaOutfitCheck = 0
;--------------------------------

; Debug variables (ignore)
global $debugDistrictAndCombatCheckEnabled = 0
global $debugOutfitCheckEnabled = 1
;--------------------------------

[Present]
; District and Combat Check
if $combatAerospaceCity == 1
	$districtAndCombatCheck = 1
	;Debug
	if $debugDistrictAndCombatCheckEnabled == 1
		run = CommandListDebugCombatInfo
	endif
else if $freeroam == 1
	$districtAndCombatCheck = 2
	;Debug
	if $debugDistrictAndCombatCheckEnabled == 1
		run = CommandListDebugFreeroamInfo
	endif
else if $combat == 1
	$districtAndCombatCheck = 1
	;Debug
	if $debugDistrictAndCombatCheckEnabled == 1
		run = CommandListDebugCombatInfo
	endif
else 
    $districtAndCombatCheck = 0
endif
;--------------------------------

; Belle Outfit Check
if $belleDefaultOutfit == 1
	$belleOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $belleYunkuiOutfit == 1
	$belleOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugYunkuiOutfitInfo
	endif
else if $belleSwimsuitOutfit == 1
	$belleOutfitCheck = 3
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugSwimsuitOutfitInfo
	endif
else
    $belleOutfitCheck = 0
endif
;--------------------------------

; Wise Outfit Check
if $wiseDefaultOutfit == 1
	$wiseOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $wiseYunkuiOutfit == 1
	$wiseOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugYunkuiOutfitInfo
	endif
else if $wiseSwimsuitOutfit == 1
	$wiseOutfitCheck = 3
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugSwimsuitOutfitInfo
	endif
else
    $wiseOutfitCheck = 0
endif
;--------------------------------

; Nicole Outfit Check
if $nicoleDefaultOutfit == 1
	$nicoleOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $nicoleCutieOutfit == 1
	$nicoleOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugAdditionalOutfitInfo
	endif
else
    $nicoleOutfitCheck = 0
endif
;--------------------------------

; Vivian Outfit Check
if $vivianDefaultOutfit == 1
	$vivianOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $vivianSwimsuitOutfit == 1
	$vivianOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugSwimsuitOutfitInfo
	endif
else
    $vivianOutfitCheck = 0
endif
;--------------------------------

; Yuzuha Outfit Check
if $yuzuhaDefaultOutfit == 1
	$yuzuhaOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $yuzuhaSwimsuitOutfit == 1
	$yuzuhaOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugSwimsuitOutfitInfo
	endif
else
    $yuzuhaOutfitCheck = 0
endif
;--------------------------------

; Alice Outfit Check
if $aliceDefaultOutfit == 1
	$aliceOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $aliceSwimsuitOutfit == 1
	$aliceOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugSwimsuitOutfitInfo
	endif
else
    $aliceOutfitCheck = 0
endif
;--------------------------------

; Sunna Outfit Check
if $sunnaDefaultOutfit == 1
	$sunnaOutfitCheck = 1
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugDefaultOutfitInfo
	endif
else if $sunnaMaidOutfit == 1
	$sunnaOutfitCheck = 2
	;Debug
	if $debugOutfitCheckEnabled == 1
		run = CommandListDebugAdditionalOutfitInfo
	endif
else
    $sunnaOutfitCheck = 0
endif
;--------------------------------

run = CommandListResetValues
;--------------------------------

[Freeroam]
; Detect freeroam
[TextureOverrideButtonUIRigth]
hash = a2975595
match_priority = 0
$freeroam = 1

[TextureOverrideMenueIcons]
hash = 1c81a3b5
match_priority = 0
$freeroam = 1
;--------------------------------

[Combat]
; Detect combat
[TextureOverrideCombatIcons]
hash = 272d39a7
match_priority = 0
$combat = 1

[TextureOverrideAerospaceCityCombatIcons]
hash = 92c264fb
match_priority = 0
$combatAerospaceCity = 1
;--------------------------------

[Belle]
; Detect Belle default outfit
[TextureOverrideDefaultBelleBodyA]
hash = 1817f3ca
match_priority = 0
$belleDefaultOutfit = 1

; Detect Belle yunkui summit outfit
[TextureOverrideYunkuiBelleBodyA]
hash = d509bdd4
match_priority = 0
$belleYunkuiOutfit = 1

; Detect Belle swimsuit outfit
[TextureOverrideSwimsuitBelleBodyA]
hash = 43ed3c22
match_priority = 0
$belleSwimsuitOutfit = 1
;--------------------------------

[Wise]
; Detect Wise default outfit
[TextureOverrideDefaultWiseBodyA]
hash = 8d6acf4e	
match_priority = 0
$wiseDefaultOutfit = 1

; Detect Wise yunkui summit outfit
[TextureOverrideYunkuiWiseBodyA]
hash = 6acc1eb8
match_priority = 0
$wiseYunkuiOutfit = 1

; Detect Wise swimsuit outfit
[TextureOverrideSwimsuitWiseBodyA]
hash = 4fe696c8
match_priority = 0
$wiseSwimsuitOutfit = 1
;--------------------------------

[Nicole]
; Detect Nicole default outfit
[TextureOverrideDefaultNicoleBodyA]
hash = 5a4c1ef3
match_priority = 0
$nicoleDefaultOutfit = 1

; Detect Nicole cutie outfit
[TextureOverrideCutieNicoleBodyA]
hash = 52842f31
match_priority = 0
$nicoleCutieOutfit = 1
;--------------------------------

[Vivian]
; Detect Vivian default outfit
[TextureOverrideDefaultVivianBodyA]
hash = cd609d98
match_priority = 0
$vivianDefaultOutfit = 1

; Detect Vivian swimsuit outfit
[TextureOverrideSwimsuitVivianBodyA]
hash = 3060793b
match_priority = 0
$vivianSwimsuitOutfit = 1
;--------------------------------

[Yuzuha]
; Detect Yuzuha default outfit
[TextureOverrideDefaultYuzuhaBodyA]
hash = 5144c409	
match_priority = 0
$yuzuhaDefaultOutfit = 1

; Detect Yuzuha swimsuit outfit
[TextureOverrideSwimsuitYuzuhaBodyA]
hash = b298482d
match_priority = 0
$yuzuhaSwimsuitOutfit = 1
;--------------------------------

[Alice]
; Detect Alice default outfit
[TextureOverrideDefaultAliceBodyA]
hash = 8a512b21
match_priority = 0
$aliceDefaultOutfit = 1

; Detect Alice swimsuit outfit
[TextureOverrideSwimsuitAliceBodyA]
hash = cf8612e6
match_priority = 0
$aliceSwimsuitOutfit = 1

[Sunna]
; Detect Sunna default outfit
[TextureOverrideDefaultSunnaBodyA]
hash = b3c6ea5a
match_priority = 0
$sunnaDefaultOutfit = 1

; Detect Sunna maid outfit
[TextureOverrideMaidSunnaBodyA]
hash = ee17c9a2
match_priority = 0
$sunnaMaidOutfit = 1
;--------------------------------

; Reset all temp. values
[CommandListResetValues]
$combat = 0
$combatAerospaceCity = 0
$freeroam = 0
$belleDefaultOutfit = 0
$belleYunkuiOutfit = 0
$belleSwimsuitOutfit = 0
$wiseDefaultOutfit = 0
$wiseYunkuiOutfit = 0
$wiseSwimsuitOutfit = 0
$nicoleDefaultOutfit = 0
$nicoleCutieOutfit = 0
$vivianDefaultOutfit = 0
$vivianSwimsuitOutfit = 0
$yuzuhaDefaultOutfit = 0
$yuzuhaSwimsuitOutfit = 0
$aliceDefaultOutfit = 0
$aliceSwimsuitOutfit = 0
$sunnaDefaultOutfit = 0
$sunnaMaidOutfit = 0
;--------------------------------

; For Debugging, ignore
[CommandListDebugCombatInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugCombatInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[CommandListDebugFreeroamInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugFreeroamInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[CommandListDebugDefaultOutfitInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugDefaultOutfitInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[CommandListDebugYunkuiOutfitInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugYunkuiOutfitInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[CommandListDebugSwimsuitOutfitInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugSwimsuitOutfitInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[CommandListDebugAdditionalOutfitInfo]
pre Resource\ShaderFixes\help.ini\Notification = ResourceDebugAdditionalOutfitInfo
pre run = CustomShader\ShaderFixes\help.ini\FormatText
pre $\ShaderFixes\help.ini\notification_timeout = time + 0.0

[ResourceDebugCombatInfo]
type = Buffer
data = "Is in combat"

[ResourceDebugFreeroamInfo]
type = Buffer
data = "Is in freeroam"

[ResourceDebugDefaultOutfitInfo]
type = Buffer
data = "Default outfit"

[ResourceDebugYunkuiOutfitInfo]
type = Buffer
data = "Yunkui outfit"

[ResourceDebugSwimsuitOutfitInfo]
type = Buffer
data = "Swimsuit outfit"

[ResourceDebugAdditionalOutfitInfo]
type = Buffer
data = "Additional outfit"
